In [9]:
#find out what the distributions look like
import pandas as pd

In [10]:
#study 1
generations = pd.read_csv('https://raw.githubusercontent.com/gokulsrin/PossibilityGeneration/main/Full/modifiedgenerationfull.csv')
information = pd.read_csv('https://raw.githubusercontent.com/gokulsrin/PossibilityGeneration/main/Full/modifiedinformationfull.csv')

In [11]:
# Study 2
generations2 = pd.read_csv('https://raw.githubusercontent.com/gokulsrin/PossibilityGeneration/main/FullV2/generations_table_full.csv')
information2 = pd.read_csv('https://raw.githubusercontent.com/gokulsrin/PossibilityGeneration/main/FullV2/information_table_full.csv')

In [12]:
#study 3 - apparently we lack the demo. data
df3 = pd.read_csv('https://raw.githubusercontent.com/gokulsrin/PossibilityGeneration/main/TimeData/generationLD%20(1).csv')

In [14]:
information = information.append(information2)

In [18]:
information

     Unnamed: 0                        id   age  ... panas_pos panas_neg openness
0           0.0          0fHXbalW6zgVLiwg  35.0  ...         0         0        0
1           1.0          1727FYFvuGobtXXS  43.0  ...         0         0        0
2           2.0          1Pxv55J6gBK04IFj  30.0  ...         0         0        0
3           3.0          1SczUqX7VCwAfGkB  63.0  ...         0         0        0
4           4.0          2r7EA4sVKkUR5rKe  30.0  ...         0         0        0
..          ...                       ...   ...  ...       ...       ...      ...
165         NaN  5acbead40527ba0001c2680a  27.0  ...        21         0       27
166         NaN  5fb3d71c3144730009fe4a7b  52.0  ...        36         0       33
167         NaN  5c670a430d80fd00014264f9  36.0  ...        34         0       34
168         NaN  5f37f046d1a0bd2af1cb0ce6  61.0  ...        31         0       34
169         NaN  5dfa56fddc265f7ac3bee209  43.0  ...        33         0       36

[367 rows x 14 columns]

In [22]:

#mean age 
print(information['age'].mean(axis=0))
print(information['age'].std(axis=0))
# gender distribution 
num_female = 0 
for gender in information['gender']:
  if gender.lower() == "female":
    num_female += 1
print(num_female/len(information['gender']))

41.22950819672131
12.369286012935255
0.5640326975476839